#!/usr/bin/env perl

use strict;
use warnings;
use v5.18.1;

use Net::AMQP::RabbitMQ;

my $mq = Net::AMQP::RabbitMQ->new();

$mq->connect("localhost", { user => "guest", password => "guest"});

$mq->channel_open(1);

$mq->exchange_declare(1, "amq.direct",
{ exchange_type => 'direct',
  durable       => 1
});

$mq->queue_declare(1,'test1');

my $val = 0;

while (1) {
  $mq->publish(1, "test1", $val++);
  sleep(1);
}
