#!/usr/bin/env perl

use strict;
use warnings;
use v5.20;

use DTrace::Consumer;
use Data::Dumper;


my $dtc = DTrace::Consumer->new();

$dtc->strcompile('profile-397Hz/ arg0 / { @s[stack()] = count(); }');
$dtc->go();

while (1) {
  $dtc->aggwalk(
    sub {
      say Dumper( \@_ );
    }
  );
}

#my $dtrace_script =

# Capture Filesystem Operation Latency data
#my $dtrace_options = [ [ qw( dynvarsize   32m ) ],
#                       [ qw( cleanrate  137Hz ) ],
#                     ];
#my $dtrace_capture =
#  PA::Capture::DTrace->new( client         => $client,
#    # loop           => $loop,
#                            dtrace_script  => $dtrace_script,
#                            stat_name      => 'fsop_lat',
#                            dtrace_options => $dtrace_options );

