#!/usr/bin/env perl

use v5.20;
use strict;
use warnings;

use FindBin qw($Bin);

use lib "$Bin/../lib";

use PA::Schema;
use Data::Dumper;

use DateTime             qw();

my $connect_info = { dsn => 'DBI:Pg:dbname=template1;host=localhost;port=15432', user => 'postgres', password => '' };

my $schema = PA::Schema->connect(
  $connect_info
);

my $host_ids = {};
my $hosts_rs   = $schema->resultset( 'Host' );
my $vmstat_rs  = $schema->resultset( 'Vmstat' );
my $arcstat_rs = $schema->resultset( 'Arcstat' );

my $hostname = "nydevsol10";
my $host_record =
     $hosts_rs->find({ name => $hostname });


my $record_count =
  $arcstat_rs->search_by_host($host_record->id)->count();

my @lines = 
  $arcstat_rs->search_by_host_sorted($host_record->id)->all;

#say Dumper( \@lines );

my @lines = 
  $arcstat_rs->host_hit_rate($host_record->id)->all;

#say Dumper( \@lines );
foreach my $row (@lines) {
  say $row->get_column('hit_rate_per_sec');
}

exit;
