#!/usr/bin/env perl

use strict;
use warnings;

use IO::Async::Loop;

my $loop = IO::Async::Loop->new;

$loop->open_child(
  command => [ "/usr/bin/mdb", "-k" ];

  stdout => {
    on_read => sub {
      my $stream, $buffref, $eof ) = @_;
    },
  },

  stdin  => {
    on_read => sub {
    },
  },

);
