#!/usr/bin/env perl

use Log::Log4perl;

my $conf = q{
log4perl.category = INFO, FWR
log4perl.appender.FWR           = Log::Dispatch::FileWriteRotate
log4perl.appender.FWR.dir       = /tmp
log4perl.appender.FWR.prefix    = memstat
log4perl.appender.FWR.period    = daily
log4perl.appender.FWR.histories = 7
log4perl.appender.FWR.layout    = Log::Log4perl::Layout::SimpleLayout
};

Log::Log4perl::init( \$conf );

my $log = Log::Log4perl::get_logger();

$log->info("TESTING");

